# action.yml
name: 'Build in docker'
description: 'Builds the debian package for the service in a docker container'

on: [push]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v5
   
   - name: Containerized Build
     uses: ./.github/workflows/dockerbuild/action


# runs:
#   using: 'docker'
#   image: 'Dockerfile'